# Generated by Django 3.0.5 on 2020-04-28 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('measuremeterdata', '0001_initial'), ('measuremeterdata', '0002_auto_20200427_1804'), ('measuremeterdata', '0003_measure_isregional'), ('measuremeterdata', '0004_auto_20200427_1810'), ('measuremeterdata', '0005_auto_20200428_1556'), ('measuremeterdata', '0006_measuretype_comment'), ('measuremeterdata', '0007_auto_20200428_1942'), ('measuremeterdata', '0008_auto_20200428_2005')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeasureCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MeasureType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='measuremeterdata.MeasureCategory')),
                ('comment', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField(blank=True, null=True)),
                ('country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='measuremeterdata.Country')),
                ('type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='measuremeterdata.MeasureType')),
                ('isregional', models.BooleanField(default=False)),
                ('sources', models.TextField(blank=True, max_length=300)),
            ],
        ),
    ]
