# Generated by Django 3.0.5 on 2020-04-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0002_auto_20200427_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='isregional',
            field=models.BooleanField(default=False),
        ),
    ]
