# Generated by Django 3.0.5 on 2020-04-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0003_measure_isregional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='measure',
            name='start',
            field=models.DateField(),
        ),
    ]
