# Generated by Django 3.0.5 on 2020-04-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0003_measure_isactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measure',
            name='isactive',
        ),
        migrations.AddField(
            model_name='measuretype',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
    ]
