# Generated by Django 3.0.5 on 2020-04-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0004_auto_20200427_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='source',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
    ]
