# Generated by Django 3.0.5 on 2020-04-30 08:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0004_auto_20200429_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='content',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
