# Generated by Django 3.0.5 on 2020-04-30 08:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0005_measure_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measure',
            name='content',
        ),
        migrations.AlterField(
            model_name='measure',
            name='comment',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
