# Generated by Django 3.0.5 on 2020-04-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0006_measuretype_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='measuretype',
            name='comment',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
