# Generated by Django 3.0.5 on 2020-04-30 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0006_auto_20200430_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='category',
            new_name='continent',
        ),
    ]
