# Generated by Django 3.0.5 on 2020-04-30 10:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0007_auto_20200430_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='comment',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='measuretype',
            name='comment',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
