# Generated by Django 3.0.5 on 2020-04-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0007_auto_20200428_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measure',
            name='source',
        ),
        migrations.AddField(
            model_name='measure',
            name='sources',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='measure',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
