# Generated by Django 3.0.5 on 2020-04-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0009_auto_20200430_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='sources',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
