# Generated by Django 3.0.5 on 2020-05-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0010_auto_20200430_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='measuretype',
            name='partial',
            field=models.BooleanField(default=False),
        ),
    ]
