# Generated by Django 3.0.5 on 2020-05-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0011_measuretype_partial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measuretype',
            name='partial',
        ),
        migrations.AddField(
            model_name='measure',
            name='partial',
            field=models.BooleanField(default=False),
        ),
    ]
