# Generated by Django 3.0.5 on 2020-05-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0012_auto_20200501_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='sources',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
