# Generated by Django 3.0.5 on 2020-05-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0014_measure_none'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
