# Generated by Django 3.0.5 on 2020-05-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0015_auto_20200501_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='measuretype',
            name='tooltip_nonpartial',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='measuretype',
            name='tooltip_partial',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
