# Generated by Django 3.0.5 on 2020-05-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0016_auto_20200502_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='mapcode_europe',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
