# Generated by Django 3.0.5 on 2020-05-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0017_country_mapcode_europe'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='level',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Partial'), (2, 'Full')], default=0),
        ),
    ]
