# Generated by Django 3.0.5 on 2020-05-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0018_measure_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
    ]
