# Generated by Django 3.0.5 on 2020-05-15 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0021_casesdeaths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casesdeaths',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
