# Generated by Django 3.0.5 on 2020-05-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0022_auto_20200515_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='casesdeaths',
            name='deathstotal',
            field=models.IntegerField(default=0),
        ),
    ]
