# Generated by Django 3.0.5 on 2020-05-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0023_casesdeaths_deathstotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='average_death_per_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='average_death_per_day_peak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='avg_desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='avg_peak_desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
