# Generated by Django 3.0.5 on 2020-05-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0024_auto_20200519_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='average_death_per_day',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='country',
            name='average_death_per_day_peak',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='country',
            name='avg_desc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='avg_peak_desc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
