# Generated by Django 3.0.5 on 2020-05-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0025_auto_20200521_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='source_death',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
