# Generated by Django 3.0.5 on 2020-05-30 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0027_auto_20200523_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='casesdeaths',
            name='cases_per_mio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='country',
            name='population',
            field=models.IntegerField(default=1),
        ),
    ]
