# Generated by Django 3.0.5 on 2020-05-31 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0028_auto_20200531_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casesdeaths',
            name='cases_per_mio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
