# Generated by Django 3.0.5 on 2020-06-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0030_casesdeaths_cases_per_mio_seven'),
    ]

    operations = [
        migrations.AddField(
            model_name='measuretype',
            name='icon',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
