# Generated by Django 3.0.5 on 2020-07-03 17:55

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0031_measuretype_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='CHCanton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CHMeasureType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('comment', ckeditor.fields.RichTextField(blank=True)),
                ('tooltip_level1', models.CharField(blank=True, max_length=200)),
                ('tooltip_level2', models.CharField(blank=True, max_length=200)),
                ('tooltip_level3', models.CharField(blank=True, max_length=200)),
                ('tooltip_level4', models.CharField(blank=True, max_length=200)),
                ('isactive', models.BooleanField(default=True)),
                ('icon', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CHMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('level', models.IntegerField(choices=[(0, 'Level 1'), (1, 'Level 2'), (2, 'Level 3'), (3, 'Level 4')], default=0)),
                ('comment', ckeditor.fields.RichTextField(blank=True)),
                ('sources', models.TextField(blank=True, max_length=300)),
                ('canton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measuremeterdata.CHCanton')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measuremeterdata.MeasureType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
