# Generated by Django 3.0.5 on 2020-07-03 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0032_chcanton_chmeasure_chmeasuretype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chmeasure',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measuremeterdata.CHMeasureType'),
        ),
    ]
