# Generated by Django 3.0.5 on 2020-07-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0033_auto_20200703_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='chmeasure',
            name='isregional',
            field=models.BooleanField(default=False),
        ),
    ]
