# Generated by Django 3.0.5 on 2020-08-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0035_auto_20200804_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='casesdeaths',
            name='cases_past14days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='chcases',
            name='cases_past14days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
    ]
