# Generated by Django 3.0.5 on 2020-08-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0036_auto_20200805_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='chcases',
            name='cases_past10days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AddField(
            model_name='chcases',
            name='cases_past7days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
    ]
