# Generated by Django 3.0.5 on 2020-08-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0037_auto_20200816_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='casesdeaths',
            name='deaths_per100k',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='casesdeaths',
            name='deathstotal_per100k',
            field=models.IntegerField(default=0),
        ),
    ]
