# Generated by Django 3.0.5 on 2020-08-19 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0038_auto_20200819_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casesdeaths',
            name='deaths_per100k',
        ),
        migrations.RemoveField(
            model_name='casesdeaths',
            name='deathstotal_per100k',
        ),
    ]
