# Generated by Django 3.0.5 on 2020-08-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0040_auto_20200819_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casesdeaths',
            name='deaths_per100k',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='casesdeaths',
            name='deaths_total_per100k',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9),
        ),
    ]
