# Generated by Django 3.0.5 on 2020-08-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0042_auto_20200819_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='casesdeaths',
            name='cases_past7days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
    ]
