# Generated by Django 3.0.5 on 2020-08-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0043_casesdeaths_cases_past7days'),
    ]

    operations = [
        migrations.AddField(
            model_name='chcanton',
            name='swisstopo_id',
            field=models.IntegerField(default=1),
        ),
    ]
