# Generated by Django 3.0.5 on 2020-08-31 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0044_chcanton_swisstopo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chcanton',
            name='level',
            field=models.IntegerField(choices=[(0, 'Canton'), (1, 'Disctrict'), (2, 'Commune')], default=0),
        ),
    ]
