# Generated by Django 3.0.5 on 2020-09-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0045_chcanton_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='casesdeaths',
            name='deaths_past14days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
    ]
