# Generated by Django 3.0.5 on 2020-09-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0046_casesdeaths_deaths_past14days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chcanton',
            name='swisstopo_id',
            field=models.CharField(max_length=200),
        ),
    ]
