# Generated by Django 3.0.5 on 2020-09-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0047_auto_20200914_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='iso_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='link_dashboard',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
