# Generated by Django 3.0.5 on 2020-10-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0052_auto_20200930_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='has_measures',
            field=models.BooleanField(default=True),
        ),
    ]
