# Generated by Django 3.0.5 on 2020-10-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0055_auto_20201006_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='belprovince',
            name='hasc',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
