# Generated by Django 3.0.5 on 2020-10-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0057_auto_20201024_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='chcases',
            name='development7to7',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='chcanton',
            name='level',
            field=models.IntegerField(choices=[(0, 'Canton'), (1, 'Disctrict'), (2, 'Commune'), (3, 'Federation')], default=0),
        ),
    ]
