# Generated by Django 3.0.5 on 2020-10-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0058_auto_20201026_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='casesdeaths',
            name='development7to7',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
    ]
