# Generated by Django 3.0.5 on 2020-10-27 09:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0059_casesdeaths_development7to7'),
    ]

    operations = [
        migrations.AddField(
            model_name='chmeasure',
            name='comment_orig',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
