# Generated by Django 3.0.5 on 2020-10-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0060_chmeasure_comment_orig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chmeasure',
            name='sources',
            field=models.TextField(blank=True, max_length=900),
        ),
    ]
