# Generated by Django 3.0.5 on 2020-11-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0061_auto_20201027_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='casesdeaths',
            name='deathstotal_peak',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='casesdeaths',
            name='deathstotal',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True),
        ),
    ]
