# Generated by Django 3.0.5 on 2020-11-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0063_auto_20201110_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='average_death_per_day',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=17),
        ),
        migrations.AlterField(
            model_name='country',
            name='average_death_per_day_peak',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=17),
        ),
    ]
