# Generated by Django 3.0.5 on 2020-11-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0064_auto_20201110_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='r0low',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=17),
        ),
        migrations.AddField(
            model_name='country',
            name='r0median',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=17),
        ),
        migrations.AddField(
            model_name='country',
            name='r0peak',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=17),
        ),
        migrations.AlterField(
            model_name='country',
            name='peak_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
