# Generated by Django 3.0.5 on 2020-11-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0065_auto_20201121_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='r0low',
        ),
        migrations.RemoveField(
            model_name='country',
            name='r0median',
        ),
        migrations.RemoveField(
            model_name='country',
            name='r0peak',
        ),
        migrations.AddField(
            model_name='casesdeaths',
            name='r0low',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=17),
        ),
        migrations.AddField(
            model_name='casesdeaths',
            name='r0median',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=17),
        ),
        migrations.AddField(
            model_name='casesdeaths',
            name='r0peak',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=17),
        ),
    ]
