# Generated by Django 3.0.5 on 2020-11-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0066_auto_20201121_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casesdeaths',
            name='r0low',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='casesdeaths',
            name='r0median',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='casesdeaths',
            name='r0peak',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=17, null=True),
        ),
    ]
