# Generated by Django 3.0.5 on 2020-12-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0069_chdeaths'),
    ]

    operations = [
        migrations.AddField(
            model_name='chdeaths',
            name='deaths15',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chdeaths',
            name='deaths19',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
