# Generated by Django 3.0.5 on 2020-12-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0070_auto_20201201_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='casesdeaths',
            name='tests',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casesdeaths',
            name='tests_per_mio',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=17, null=True),
        ),
    ]
