# Generated by Django 3.0.5 on 2020-12-05 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0071_auto_20201205_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casesdeaths',
            old_name='tests_per_mio',
            new_name='tests_smoothed_per_thousand',
        ),
    ]
