# Generated by Django 3.0.5 on 2020-12-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0075_casesdeaths_deathstotal_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='chcases',
            name='mobility_recreation',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=17, null=True),
        ),
        migrations.AddField(
            model_name='chcases',
            name='mobility_transit',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=17, null=True),
        ),
        migrations.AddField(
            model_name='chcases',
            name='mobility_workplace',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=17, null=True),
        ),
    ]
