# Generated by Django 3.0.5 on 2020-12-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0076_auto_20201229_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='casesdeaths',
            name='deaths_past7days',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
    ]
