# Generated by Django 3.0.5 on 2021-01-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0078_oxfordmeasure_oxfordmeasuretype'),
    ]

    operations = [
        migrations.AddField(
            model_name='oxfordmeasure',
            name='comment',
            field=models.CharField(default='', max_length=200),
        ),
    ]
