# Generated by Django 3.0.5 on 2021-01-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0079_oxfordmeasure_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oxfordmeasuretype',
            name='text_level0',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='oxfordmeasuretype',
            name='text_level1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='oxfordmeasuretype',
            name='text_level2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='oxfordmeasuretype',
            name='text_level3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='oxfordmeasuretype',
            name='text_level4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
