# Generated by Django 3.0.5 on 2021-01-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0080_auto_20210103_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='oxfordmeasure',
            name='last_level',
            field=models.IntegerField(default=0),
        ),
    ]
