# Generated by Django 3.0.5 on 2021-01-07 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0082_auto_20210104_2106'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Measure',
            new_name='Measure_old',
        ),
        migrations.RenameModel(
            old_name='MeasureType',
            new_name='MeasureType_old',
        ),
    ]
