# Generated by Django 3.0.5 on 2021-01-07 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0083_auto_20210107_1244'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OxfordMeasure',
            new_name='CountryMeasure',
        ),
        migrations.RenameModel(
            old_name='OxfordMeasureType',
            new_name='CountryMeasureType',
        ),
    ]
