# Generated by Django 3.0.5 on 2021-01-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0084_auto_20210107_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrymeasure',
            name='isregional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='countrymeasure',
            name='source',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
