# Generated by Django 3.0.5 on 2021-01-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0085_auto_20210107_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrymeasure',
            name='isregional',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
