# Generated by Django 3.0.5 on 2021-01-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0086_auto_20210107_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrymeasure',
            name='isregional',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='countrymeasure',
            name='last_level',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
