# Generated by Django 3.0.5 on 2021-01-18 23:04

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0088_auto_20210107_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='CHStringency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('KOF_value', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('KOF_value_before', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('comment', ckeditor.fields.RichTextField(blank=True)),
                ('canton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measuremeterdata.CHCanton')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
