# Generated by Django 3.0.5 on 2021-01-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0089_chstringency'),
    ]

    operations = [
        migrations.AddField(
            model_name='chdeaths',
            name='deaths21',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
