# Generated by Django 3.0.5 on 2021-02-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0090_chdeaths_deaths21'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoomsdayClock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('hosp_cov19_patients', models.IntegerField(blank=True, null=True)),
                ('hosp_capacity', models.IntegerField(blank=True, null=True)),
                ('hosp_date', models.DateField(blank=True, null=True)),
                ('positivity', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('positivity_date', models.DateField(blank=True, null=True)),
                ('r1_value', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('r1_date', models.DateField(blank=True, null=True)),
                ('r2_value', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('r2_date', models.DateField(blank=True, null=True)),
                ('r3_value', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('r3_date', models.DateField(blank=True, null=True)),
                ('r4_value', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('r4_date', models.DateField(blank=True, null=True)),
                ('r5_value', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('r5_date', models.DateField(blank=True, null=True)),
                ('incidence_mar1', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('incidence_latest', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('incidence_latest_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
