# Generated by Django 3.0.5 on 2021-02-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0091_doomsdayclock'),
    ]

    operations = [
        migrations.AddField(
            model_name='doomsdayclock',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
