# Generated by Django 3.0.5 on 2021-03-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0093_doomsdayclock_r_okay'),
    ]

    operations = [
        migrations.AddField(
            model_name='doomsdayclock',
            name='r6_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doomsdayclock',
            name='r6_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='doomsdayclock',
            name='r7_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doomsdayclock',
            name='r7_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='doomsdayclock',
            name='r_average',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
    ]
