# Generated by Django 3.0.5 on 2021-03-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0094_auto_20210302_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='casesdeaths',
            name='death_to_cases',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
    ]
