# Generated by Django 3.0.5 on 2021-03-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0096_casesdeaths_people_vaccinated_per_hundred'),
    ]

    operations = [
        migrations.AddField(
            model_name='doomsdayclock',
            name='hosp1_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doomsdayclock',
            name='hosp1_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='doomsdayclock',
            name='hosp2_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doomsdayclock',
            name='hosp2_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='doomsdayclock',
            name='hosp3_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doomsdayclock',
            name='hosp3_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='doomsdayclock',
            name='hosp4_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doomsdayclock',
            name='hosp4_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='doomsdayclock',
            name='hosp5_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doomsdayclock',
            name='hosp5_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='doomsdayclock',
            name='hosp6_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doomsdayclock',
            name='hosp6_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='doomsdayclock',
            name='hosp7_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doomsdayclock',
            name='hosp7_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='doomsdayclock',
            name='hosp_average',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
    ]
