# Generated by Django 3.0.5 on 2021-04-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0097_auto_20210324_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='doomsdayclock',
            name='hosp_average_7d',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='doomsdayclock',
            name='hosp_cov19_patients_7d',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doomsdayclock',
            name='incidence_latest_7d',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='doomsdayclock',
            name='r_average_7d',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
    ]
