# Generated by Django 3.0.5 on 2021-04-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0098_auto_20210409_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='chcases',
            name='vacc_perpop_7d',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
