# Generated by Django 3.0.5 on 2021-04-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0099_chcases_vacc_perpop_7d'),
    ]

    operations = [
        migrations.AddField(
            model_name='doomsdayclock',
            name='deaths_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='doomsdayclock',
            name='deaths_value_7d',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='doomsdayclock',
            name='positivity_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='doomsdayclock',
            name='positivity_value_7d',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='doomsdayclock',
            name='vacc_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doomsdayclock',
            name='vacc_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='doomsdayclock',
            name='vacc_value_7d',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
    ]
