# Generated by Django 3.0.5 on 2021-04-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0101_auto_20210421_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='chcases',
            name='vacc_perpop',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='chcases',
            name='vacc_total',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
