# Generated by Django 3.0.5 on 2021-04-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0102_auto_20210423_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chcases',
            name='vacc_total',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
    ]
