# Generated by Django 3.0.5 on 2021-04-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0103_auto_20210423_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chcases',
            name='vacc_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
