# Generated by Django 3.0.5 on 2021-11-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0105_doomsdayclock_cur_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='casesdeaths',
            name='hosp_per_million',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
    ]
