# Generated by Django 3.0.5 on 2022-02-20 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('measuremeterdata', '0106_casesdeaths_hosp_per_million'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCasesDeaths',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('date', models.DateField()),
                ('cases', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('deathstotal', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('deathstotal_peak', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('deathstotal_average', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('deaths_past14days', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('deaths_past7days', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('cases_past14days', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('cases_past7days', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('positivity', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('development7to7', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('r0peak', models.DecimalField(blank=True, decimal_places=5, max_digits=17, null=True)),
                ('r0low', models.DecimalField(blank=True, decimal_places=5, max_digits=17, null=True)),
                ('r0median', models.DecimalField(blank=True, decimal_places=5, max_digits=17, null=True)),
                ('tests', models.IntegerField(blank=True, null=True)),
                ('tests_smoothed_per_thousand', models.DecimalField(blank=True, decimal_places=5, max_digits=17, null=True)),
                ('stringency_index', models.DecimalField(blank=True, decimal_places=5, max_digits=17, null=True)),
                ('death_to_cases', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('people_vaccinated_per_hundred', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('hosp_per_million', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('country', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='measuremeterdata.Country')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical cases deaths',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
