# Generated by Django 3.0.5 on 2022-02-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0107_historicalcasesdeaths'),
    ]

    operations = [
        migrations.AddField(
            model_name='chdeaths',
            name='deaths22',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
