# Generated by Django 3.0.5 on 2022-11-19 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measuremeterdata', '0108_chdeaths_deaths22'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalCasesDeaths',
        ),
    ]
