# Generated by Django 3.0.5 on 2020-10-25 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BELAgeGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('population', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BELProvince',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('name_source', models.CharField(blank=True, max_length=200, null=True)),
                ('hasc', models.CharField(blank=True, max_length=5, null=True)),
                ('population', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BELCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('cases0_9', models.IntegerField(default=0)),
                ('cases10_19', models.IntegerField(default=0)),
                ('cases20_29', models.IntegerField(default=0)),
                ('cases30_39', models.IntegerField(default=0)),
                ('cases40_49', models.IntegerField(default=0)),
                ('cases50_59', models.IntegerField(default=0)),
                ('cases60_69', models.IntegerField(default=0)),
                ('cases70_79', models.IntegerField(default=0)),
                ('cases80_89', models.IntegerField(default=0)),
                ('cases90plus', models.IntegerField(default=0)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riskcalc.BELProvince')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
